### PR TITLE
BSidesSF2019

### PR DESCRIPTION
**Pull request by SJChang**

### CODE REVIEW

**Comment by zwade** [comment]
Looks good. Want me to merge it?

**Comment by SJChang** [comment]
Would that be too entry-level write-ups...?
I might write some more BSideSF challenge write-ups so that the folder
would not only have one file..

Susie

Zach Wade <notifications@github.com> 於 2019年3月6日 週三 下午1:39寫道：

**Comment by zwade** [comment]
Oh, don't worry about that. I would recommend merging this, then adding more later if you  feel like it.

**Comment by SJChang** [comment]
sounds... good...
thanks >///<
Susie

Zach Wade <notifications@github.com> 於 2019年3月6日 週三 下午1:52寫道：

**Pull request merged**
